### ISSUE TITLE
Max string length

### ISSUE THREAD

**Issue by Djpleasant** [sifuas/CrestronDataStore#1]
Feel free to close this out if I'm wrong, but I remember reading somewhere on Labs that the string length is limited to 1600bytes. A cursory glance at the documentation didn't say anything about that (but Crestron's documentation can be lacking at times). If that length limit is accurate though, it may be worth adding some error checking or console logging to indicate that the string will be truncated (or it may just throw an error when you try to set it).

Thanks for making this public for us though!

**Comment by Djpleasant** [comment]
As I hit submit, I realized this library is meant to be used for SIMPL Windows where the 255byte limit on strings already exists. I'll go ahead and close this myself.

**Comment by sifuas** [comment]
Yeah, I just went with the built in Simpl Windows limitation. I assumed there is no need for this library a Pro program since you would just use the CrestronDataStoreStatic class directly. Thank you for taking the time to review.
